import Head from 'next/head';
import { ReactElement, useState } from 'react';
import StartScreen from '@components/StartScreen';
import Board from '@components/Board';

export default function Home(): ReactElement {
  const [start, setStart] = useState<boolean>(true);

  return (
    <div>
      <Head>
        <title>Memory Game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      { start ? 
        (<StartScreen handleClick={() => setStart(false)} />) 
        : 
        (<Board/>)
      }
    </div>
  );
}